package es.kirito.kirito.precarga.domain.models

enum class PreloadStep {

   BEGINNING, ELEMENTOS_VIEJOS,
    FESTIVOS, GRAFICOS, TURNOS, MENSAJES_ADMIN, ELEMENTOS_GENERALES, TELEINDICADORES,
    USUARIOS, ESTACIONES, GRAFICO_ACTUAL, TURNOS_COMPIS, INFO_METEOROLOGICA, NOTHING,
    FINISHED
}